# Generated by Django 3.0.7 on 2020-07-02 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 0, 32, 24, 546274, tzinfo=utc), verbose_name='Enter the published date'),
        ),
    ]
